# Generated by Django 3.2.12 on 2022-05-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name_plural': 'Questionnaire'},
        ),
        migrations.AlterModelOptions(
            name='userquestionnaire',
            options={'verbose_name_plural': 'User Questionnaire'},
        ),
    ]
